### ISSUE TITLE
FNB48S listed in udev rules but not found by script

### ISSUE THREAD

**Issue by parkerlreed** [baryluk/fnirsi-usb-power-data-logger#9]
Installed the udev rules and reloaded.

```
Bus 001 Device 003: ID 2e3c:0049 FNIRSI USB Tester
```

```
(deck@steamdeck fnirsi-usb-power-data-logger)$ ./fnirsi_logger.py 
Traceback (most recent call last):
  File "/home/deck/build/fnirsi-usb-power-data-logger/./fnirsi_logger.py", line 230, in <module>
    main()
  File "/home/deck/build/fnirsi-usb-power-data-logger/./fnirsi_logger.py", line 58, in main
    assert dev, "Device not found"
AssertionError: Device not found
(1)(deck@steamdeck fnirsi-usb-power-data-logger)$ sudo -E ./fnirsi_logger.py 
Traceback (most recent call last):
  File "/home/deck/build/fnirsi-usb-power-data-logger/./fnirsi_logger.py", line 230, in <module>
    main()
  File "/home/deck/build/fnirsi-usb-power-data-logger/./fnirsi_logger.py", line 58, in main
    assert dev, "Device not found"
AssertionError: Device not found
```

**Comment by parkerlreed** [comment]
I changed the FNB58 in the python script to match 0049 and it works. Can there be a specific case for the 48S added considering it's already in udev?

```
# FNB58
VID_FNB58 = 0x2E3C
PID_FNB58 = 0x0049
```

**Comment by baryluk** [comment]
Thanks for the feedback. Added it to the code. Hopefully it works fine.
